apiVersion: batch/v1
kind: Job
metadata:
  name: errorjob-restartpod
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: unexited-code
        image: busybox
        command: ["exit 1"]
      restartPolicy: OnFailure
