apiVersion: batch/v1
kind: Job
metadata:
  name: error-pythonjob-1
spec:
  template:
    spec:
      containers:
      - name: errorjob-python
        image: choisunguk/k8s-jobtest-error1:job1
      restartPolicy: OnFailure
